package com.helloworld.apispring.model.entity;
// Generated 13/10/2018 07:27:36 PM by Hibernate Tools 4.3.1

import javax.persistence.Transient;


/**
 * Reservas generated by hbm2java
 */
public class Reservas implements java.io.Serializable {

    private Integer idReservas;
    private Usuarios usuarios;
    private Viajes viajes;

    public Reservas() {
    }

    public Reservas(Usuarios usuarios, Viajes viajes) {
        this.usuarios = usuarios;
        this.viajes = viajes;
    }

    public Integer getIdReservas() {
        return this.idReservas;
    }

    public void setIdReservas(Integer idReservas) {
        this.idReservas = idReservas;
    }

    public Usuarios getUsuarios() {
        return this.usuarios;
    }

    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    public Viajes getViajes() {
        return this.viajes;
    }

    public void setViajes(Viajes viajes) {
        this.viajes = viajes;
    }
    @Transient//no tiene afectacion en la base de datos
    private long idViajes;

    public long getIdViajes() {
        return idViajes;
    }

    public void setIdViajes(long idViajes) {
        this.idViajes = idViajes;
    }
    @Transient//no tiene afectacion en la base de datos
    private long idUsuario;

    public long getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(long idUsuario) {
        this.idUsuario = idUsuario;
    }

}
